
POST http://localhost:3004/categories
Content-Type: application/json

{
   "name":"TV'S"
}

#########
GET http://localhost:3004/categories

##########
POST http://localhost:3004/auth/register
Content-Type: application/json

{
   "Name": "John Smith",
   "Email": "JohnS@gmail.com",
   "Password": "This123@7"

}

########
POST http://localhost:3004/auth/login
Content-Type: application/json

{
   "Email": "JohnS@gmail.com",
   "Password": "This123@7"

}

############
POST http://localhost:3004/products
Content-Type: application/json

{
   "name": "Samsung Screen",
   "description": "That looks like a picture",
   "price": 100000,
   "id": "f49bc4b8-131a-4058-a7be-abd9485e23f1"

}

########
GET http://localhost:3004/products

#########
GET http://localhost:3004/products/caa7efec-5e6a-46cb-85bc-8f38f53f65e3

########

PATCH  http://localhost:3004/products/caa7efec-5e6a-46cb-85bc-8f38f53f65e3
Content-Type: application/json

{
   "name": "Samsung 3D Screen",
   "description": "That looks like a picture",
   "price": 900000,
   "id": "f49bc4b8-131a-4058-a7be-abd9485e23f1"

}

########
DELETE http://localhost:3004/products/96353393-9764-428f-ba42-329f9129f1a3
